local f = CreateFrame("Frame")

f:RegisterEvent("PLAYER_ENTERING_WORLD")

f:SetScript("OnEvent", function(self, event, isLogin, isReload)
    SetCVar("rawMouseEnable", 1)
    print("|cff00ff00[FixMouseLookSpeed]|r Changed the rawMouseEnable to 1.")
    SetCVar("rawMouseAccelerationEnable", 0)
    SetCVar("cameraYawMoveSpeed", 30)
    print("|cff00ff00[FixMouseLookSpeed]|r Changed the cameraYawMoveSpeed to 30.")
    SetCVar("cameraPitchMoveSpeed", 30)
    print("|cff00ff00[FixMouseLookSpeed]|r Changed the cameraPitchMoveSpeed to 30.")
    SetCVar("cameraDistanceMaxZoomFactor", 2.0)
    print("|cff00ff00[FixMouseLookSpeed]|r Changed the cameraDistanceMaxZoomFactor to 2.0.")
end)